### ISSUE TITLE
Forced Evacuation

### ISSUE THREAD

**Issue by QriouZz** [DecentralCardGame/cards#113]
https://crowdcontrol.network/#/cardview/206
We want a funny beeing like Kirby or King Dedede with a oversized Leafblower who forces people out of thei houses or creatures away.

I think this might have been replaced with maintenance center? (patrick)

stefi

**Comment by QriouZz** [comment]
![supersmashbros_1033274b](https://user-images.githubusercontent.com/73444376/175308115-74572e1b-bbe9-4fd7-9bf6-9eac5e9794ba.jpg)

**Comment by AnnyBuh** [comment]
Closed because it's maintance center
