### ISSUE TITLE
Border Fortress

### ISSUE THREAD

**Issue by RuslanUfa** [DecentralCardGame/cards#128]
minor edits, compo improvement (kosta)

card updated:
https://crowdcontrol.network/#/cardview/454
(Ruslan)

**Comment by patrickwieth** [comment]
Maybe increase symmetry on the tower tops? AI likes to make it a bit too organic :D @43rozopher 
Reduce Health to 4, rest looks good to me

**Comment by 43rozopher** [comment]
right. could need some more corrections

**Comment by RuslanUfa** [comment]
accepted, corrected
