### ISSUE TITLE
Carpenter Hudson

### ISSUE THREAD

**Issue by RuslanUfa** [DecentralCardGame/cards#133]
Done: Edit, extend illu for compo and slight overpaint so it's sharper and the edges cleaner, fitting other characters like guild coach stylewise. (kosta)

Card updated (Ruslan)
https://crowdcontrol.network/#/cardview/431

complete redesign in mj (Ruslan)

corrections (kosta)

**Comment by patrickwieth** [comment]
Great card, maybe the name does no longer fit, because Billy sounds like a young boy and this is a manly man. So maybe Carpenter Gus or Carpenter Hudson or so

**Comment by RuslanUfa** [comment]
I like Hudson, updated
