### ISSUE TITLE
Carpentry

### ISSUE THREAD

**Issue by RuslanUfa** [DecentralCardGame/cards#134]
Redone in a more paintsy style? (kosta)

The new picture is good, the card is updated (Ruslan)
https://crowdcontrol.network/#/cardview/449

**Comment by patrickwieth** [comment]
- Tools should be written in capital letter: "Tools"
- The card is an action card, which is ok, but the title implies it is a thing and not an action. So the title should be changed to something that describes a process: "Equip the Carpenter", "Carpentry", "Emergency Carpenting", "Carpenting Hours" etc.
- 4 Mana is too expensive for the effect, 2 Mana might be better (still debatable if the card will be used, maybe give it insight 1 or 2 as well).

**Comment by RuslanUfa** [comment]
Changed the name to Carpentry.
Replaced Effects - Fortify 1, Insight 2, costs 2 Mana. 
Objectives:
1) That the player would want to play this card a second time to get Wisdom 4;
2) Fortify HQ because initially HQ has little life. 

maybe now it will be more interesting to play

**Comment by patrickwieth** [comment]
Now the card is very weak, maybe for 0 Mana it would see play with these effects, but most likely in a deck that wants to shoot out spells that synergy with channel abilities and cost 0 mana to storm along. In normal games where no channel synergies exist the card is even for 0 mana probably too bad. Maybe Repair ALL 2 and insight 2, for 1 mana could see play. Especially in combination with the Tax institution...

**Comment by RuslanUfa** [comment]
Okay, let's try it, updated
